server:
  port: 9000

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/cola-cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      db-name: cola-cloud
devtools: #开发工具
  project-location:
  developer:
  table-prefix:

security:
  basic:
    enabled: false
