server:
  port: 9000

spring:
    datasource:
      url: jdbc:mysql://192.168.0.119:3306/xknf?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 7771234
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      db-name: xknf
devtools: #开发工具
  project-location:
  developer:
  table-prefix:
